# Generated by Django 4.0.5 on 2022-06-27 07:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import expenditure_register.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_protocol_number', models.CharField(max_length=10, verbose_name='Αριθμός απόφασης ανάληψης υποχρέωσης')),
                ('debit_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Ανάληψης Υποχρέωσης')),
                ('diavgeia_string', models.CharField(max_length=100, verbose_name='ΑΔΑ')),
                ('diavgeia_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Ανάρτησης στη Διαύγεια')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RequestForPaymentOrInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afm', models.CharField(max_length=9, validators=[expenditure_register.validators.validate_afm], verbose_name='Α.Φ.Μ.')),
                ('creditor_is_abroad', models.BooleanField(default=False, verbose_name='Πιστωτής μόνιμα εγκατεστημένος στην αλλοδαπή')),
                ('transaction_is_commercial', models.BooleanField(default=False, verbose_name='Εμπορική Συναλλαγή')),
                ('invoice_series', models.CharField(max_length=10, verbose_name='Σειρά τιμολογίου ή άλλου φορολογικού στοιχείου')),
                ('invoice_number', models.CharField(max_length=10, verbose_name='Αριθμός Τιμολογίου ή άλλου ισοδύναμου εγγράφου')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία έκδοσης τιμολογίου ή ισοδύναμου εγγράφου')),
                ('invoice_charge_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ημερομηνία έκδοσης τιμολογίου ή ισοδύναμου εγγράφου')),
                ('invoice_reception_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία παραλαβής τιμολογίου ή ισοδύναμου εγγράφου')),
                ('service_reception_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία παραλαβής αγαθών, υπηρεσιών ή εργασιών')),
                ('service_acceptance_verification_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία έγκρισης παραλαβής αγαθών, υπηρεσιών ή εργασιών')),
                ('payment_due_date', models.DateField(default=datetime.datetime(2022, 7, 27, 7, 22, 37, 370045, tzinfo=utc), verbose_name='Ημερομηνία παραλαβής αγαθών, υπηρεσιών ή εργασιών')),
                ('obligation_creation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία δημιουργίας υποχρέωσης')),
                ('computed_maturation_start_date', models.DateField(default=datetime.datetime(2022, 6, 28, 7, 22, 37, 370078, tzinfo=utc), verbose_name='Ημερομηνία έναρξης ωρίμανσης')),
                ('computed_payment_due_date', models.DateField(default=datetime.datetime(2022, 6, 28, 7, 22, 37, 370094, tzinfo=utc), verbose_name='Ημερομηνία δημιουργίας υποχρέωσης')),
                ('payment_in_advance', models.BooleanField(default=False, verbose_name='Πληρωμή μέσω Πάγιας Προκαταβολής')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure_register.debit', verbose_name='Αριθμός απόφασης ανάληψης υποχρέωσης')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type_choice', models.CharField(choices=[('ΕΞΟΦΛΗΣΗ', 'ΕΞΟΦΛΗΣΗ'), ('ΑΠΟΡΡΙΨΗ', 'ΑΠΟΡΙΨΗ'), ('ΑΚΥΡΩΣΗ', 'ΑΚΥΡΩΣΗ')], default='ΑΠΟΔΟΧΗ', max_length=100, verbose_name='Διαχείριση πληρωμής τιμολογίου ή ισοδύναμου εγγράφου')),
                ('number', models.CharField(max_length=10, verbose_name='Αριθμός παραστατικού')),
                ('document_type', models.CharField(choices=[('ΤΑΚΤΙΚΟ ΧΡΗΜΑΤΙΚΟ ΕΝΤΑΛΜΑ', 'ΤΑΚΤΙΚΟ ΧΡΗΜΑΤΙΚΟ ΕΝΤΑΛΜΑ'), ('ΧΡΗΜΑΤΙΚΟ ΕΝΤΑΛΜΑ ΠΡΟΠΛΗΡΩΜΗΣ', 'ΧΡΗΜΑΤΙΚΟ ΕΝΤΑΛΜΑ ΠΡΟΠΛΗΡΩΜΗΣ'), ('ΕΝΤΟΛΗ ΜΕΤΑΦΟΡΑΣ', 'ΕΝΤΟΛΗ ΜΕΤΑΦΟΡΑΣ'), ('ΣΥΜΨΗΦΙΣΤΙΚΟ ΕΝΤΑΛΜΑ', 'ΣΥΜΨΗΦΙΣΤΙΚΟ ΕΝΤΑΛΜΑ'), ('ΣΥΜΨΗΦΙΣΤΙΚΟ ΕΝΤΑΛΜΑ ΣΥΝΕΠΕΙΑ ΚΑΤΑΣΧΕΣΕΩΝ', 'ΣΥΜΨΗΦΙΣΤΙΚΟ ΕΝΤΑΛΜΑ ΣΥΝΕΠΕΙΑ ΚΑΤΑΣΧΕΣΕΩΝ'), ('ΑΚΥΡΩΤΙΚΟ ΕΝΤΑΛΜΑ', 'ΑΚΥΡΩΤΙΚΟ ΕΝΤΑΛΜΑ')], default='', max_length=100, verbose_name='Είδος παραστατικού')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία παραστατικού (Απόρριψη/Ακύρωση/Εξόφληση)')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Συνολικό ποσό πληρωμής')),
                ('payment_amount_to_third_persons', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Συνολικό ποσό πληρωμής ληξιπρόθεσμων οφειλών > 90 ημερών προς τρίτους')),
                ('setoff_payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Εκ του οποίου συμψηφισμοί/παρακράτηση υπέρ Δημοσίου ή ΟΚΑ')),
                ('request_for_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure_register.requestforpaymentorinvoice', verbose_name='Αριθμός απόφασης ανάληψης υποχρέωσης')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_type', models.CharField(choices=[('ΚΡΑΤΙΚΟΣ_ΠΡΟΫΠΟΛΟΓΙΣΜΟΣ', 'ΚΡΑΤΙΚΟΣ ΠΡΟΫΠΟΛΟΓΙΣΜΟΣ'), ('ΠΡΟΓΡΑΜΜΑ ΔΗΜΟΣΙΩΝ ΕΠΕΝΔΥΣΕΩΝ', 'ΠΡΟΓΡΑΜΜΑ ΔΗΜΟΣΙΩΝ ΕΠΕΝΔΥΣΕΩΝ')], default='ΠΡΟΓΡΑΜΜΑ ΔΗΜΟΣΙΩΝ ΕΠΕΝΔΥΣΕΩΝ', max_length=32, verbose_name='Τύπος προϋπολογισμού')),
                ('year', models.PositiveSmallIntegerField(default=2022, verbose_name='Οικονομικό Έτος')),
                ('organization', models.CharField(default='1019-206', max_length=10, verbose_name='Φορέας')),
                ('special_organization', models.CharField(default='9922000', max_length=10, verbose_name='Ειδικός Φορέας')),
            ],
            options={
                'unique_together': {('budget_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ExitAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='ΑΛΕ')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(default='ΑΓΟΡΕΣ ΑΓΑΘΩΝ ΚΑΙ ΥΠΗΡΕΣΙΩΝ', max_length=10, verbose_name='Κατηγορία')),
                ('subcategory', models.CharField(max_length=10, verbose_name='Υποκατηγορία')),
                ('description', models.TextField()),
                ('expenditure_register', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='expenditure_register.expenditureregister', verbose_name='Μητρώο Δεσμεύσεων')),
            ],
        ),
        migrations.AddField(
            model_name='debit',
            name='exit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='expenditure_register.exitaccount', verbose_name='ΑΛΕ'),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disposed_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_of_disposal', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Πίστωσης')),
                ('exit_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='expenditure_register.exitaccount', verbose_name='ΑΛΕ')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.CharField(max_length=10, verbose_name='Αριθμός σύμβασης')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Ανάρτησης στη Διαύγεια')),
                ('diavgeia_string', models.CharField(max_length=100, verbose_name='ΑΔΑ')),
                ('diavgeia_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Ανάρτησης στη Διαύγεια')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure_register.debit', verbose_name='Αριθμός απόφασης ανάληψης υποχρέωσης')),
            ],
        ),
    ]
