# Generated by Django 4.0.5 on 2022-07-05 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0002_alter_expenditureregister_budget_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Διαθέσιμο Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='exitaccount',
            name='subcategory',
            field=models.CharField(choices=[('ΙΔΙΩΤΕΣ', 'ΙΔΙΩΤΕΣ'), ('ΥΠΕΡΩΡΙΕΣ ΔΙΟΙΚΗΤΙΚΩΝ', 'ΥΠΕΡΩΡΙΕΣ ΔΙΟΙΚΗΤΙΚΩΝ'), ('ΜΗ ΛΗΨΗ ΑΔΕΙΑΣ', 'ΜΗ ΛΗΨΗ ΑΔΕΙΑΣ'), ('ΑΠΟΖΗΜΙΩΣΗ ΣΑΒΒΑΤΑ-ΚΥΡΙΑΚΕΣ', 'ΑΠΟΖΗΜΙΩΣΗ ΣΑΒΒΑΤΑ-ΚΥΡΙΑΚΕΣ'), ('ΑΠΟΖΗΜΙΩΣΗ ΣΑΒΒΑΤΑ-ΚΥΡΙΑΚΕΣ (ΙΔΟΧ)', 'ΑΠΟΖΗΜΙΩΣΗ ΣΑΒΒΑΤΑ-ΚΥΡΙΑΚΕΣ (ΙΔΟΧ)'), ('ΥΠΕΡΩΡΙΕΣ', 'ΥΠΕΡΩΡΙΕΣ'), ('ΩΡΟΜΙΣΘΙΟΙ', 'ΩΡΟΜΙΣΘΙΟΙ'), ('ΥΠΕΡΩΡΙΣΕ ΣΕ ΒΟΥΛΕΥΤΙΚΑ, ΠΟΛΙΤΙΚΑ ΓΡΑΦΕΙΑ', 'ΥΠΕΡΩΡΙΣΕ ΣΕ ΒΟΥΛΕΥΤΙΚΑ, ΠΟΛΙΤΙΚΑ ΓΡΑΦΕΙΑ'), ('ΟΔΟΙΠΟΡΙΚΑ', 'ΟΔΟΙΠΟΡΙΚΑ'), ('ΕΞΟΔΑ ΜΕΤΑΚΙΝΗΣΗΣ ΜΑΘΗΤΩΝ', 'ΕΞΟΔΑ ΜΕΤΑΚΙΝΗΣΗΣ ΜΑΘΗΤΩΝ'), ('ΗΜΕΡΗΣΙΑ ΑΠΟΖΗΜΙΩΣΗ', 'ΗΜΕΡΗΣΙΑ ΑΠΟΖΗΜΙΩΣΗ'), ('ΕΠΙΤΡΟΠΕΣ ΙΔΟΧ', 'ΕΠΙΤΡΟΠΕΣ ΙΔΟΧ'), ('ΕΠΙΤΡΟΠΕΣ', 'ΕΠΙΤΡΟΠΕΣ'), ('ΤΟΚΟΙ ΑΠΌ ΕΚΤΕΛΕΣΗ ΔΙΚΑΣΤΙΚΩΝ ΑΠΟΦΆΣΕΩΝ', 'ΤΟΚΟΙ ΑΠΌ ΕΚΤΕΛΕΣΗ ΔΙΚΑΣΤΙΚΩΝ ΑΠΟΦΆΣΕΩΝ'), ('ΛΟΙΠΕΣ ΑΠΟΖΗΜΙΩΣΕΙΣ ΣΕ ΕΚΤΕΛΕΣΗ ΔΙΚΑΣΤΙΚΩΝ ΑΠΟΦΑΣΕΩΝ', 'ΛΟΙΠΕΣ ΑΠΟΖΗΜΙΩΣΕΙΣ ΣΕ ΕΚΤΕΛΕΣΗ ΔΙΚΑΣΤΙΚΩΝ ΑΠΟΦΑΣΕΩΝ'), ('ΔΙΚΑΣΤΙΚΑ', 'ΔΙΚΑΣΤΙΚΑ'), ('ΞΕΝΟΓΛΩΣΣΑ', 'ΞΕΝΟΓΛΩΣΣΑ'), ('ΕΞΟΔΑ ΔΙΑΝΥΚΤΕΡΕΥΣΗΣ', 'ΕΞΟΔΑ ΔΙΑΝΥΚΤΕΡΕΥΣΗΣ')], max_length=100, verbose_name='Υποκατηγορία'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='computed_maturation_start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 6, 11, 47, 0, 10767, tzinfo=utc), verbose_name='Ημερομηνία έναρξης ωρίμανσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='computed_payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 6, 11, 47, 0, 10783, tzinfo=utc), verbose_name='Ημερομηνία δημιουργίας υποχρέωσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 4, 11, 47, 0, 10730, tzinfo=utc), verbose_name='Ημερομηνία παραλαβής αγαθών, υπηρεσιών ή εργασιών'),
        ),
    ]
