# Generated by Django 4.0.5 on 2022-07-05 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0005_alter_requestforpaymentorinvoice_computed_maturation_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitaccount',
            name='category',
            field=models.CharField(default='ΑΓΟΡΕΣ ΑΓΑΘΩΝ ΚΑΙ ΥΠΗΡΕΣΙΩΝ', max_length=50, verbose_name='Κατηγορία'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='computed_maturation_start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 6, 11, 49, 59, 519655, tzinfo=utc), verbose_name='Ημερομηνία έναρξης ωρίμανσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='computed_payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 6, 11, 49, 59, 519671, tzinfo=utc), verbose_name='Ημερομηνία δημιουργίας υποχρέωσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 4, 11, 49, 59, 519619, tzinfo=utc), verbose_name='Ημερομηνία παραλαβής αγαθών, υπηρεσιών ή εργασιών'),
        ),
    ]
