# Generated by Django 4.0.5 on 2022-07-05 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0008_alter_requestforpaymentorinvoice_computed_maturation_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='computed_maturation_start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 6, 12, 1, 32, 36471, tzinfo=utc), verbose_name='Ημερομηνία έναρξης ωρίμανσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='computed_payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 6, 12, 1, 32, 36502, tzinfo=utc), verbose_name='Ημερομηνία δημιουργίας υποχρέωσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 4, 12, 1, 32, 36437, tzinfo=utc), verbose_name='Ημερομηνία παραλαβής αγαθών, υπηρεσιών ή εργασιών'),
        ),
    ]
