# Generated by Django 4.0.5 on 2022-07-06 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0013_alter_requestforpaymentorinvoice_computed_maturation_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='exit_account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='debit',
            old_name='exit_account',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='computed_maturation_start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 11, 15, 9, 242508, tzinfo=utc), verbose_name='Ημερομηνία έναρξης ωρίμανσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='computed_payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 11, 15, 9, 242524, tzinfo=utc), verbose_name='Ημερομηνία δημιουργίας υποχρέωσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 5, 11, 15, 9, 242472, tzinfo=utc), verbose_name='Ημερομηνία παραλαβής αγαθών, υπηρεσιών ή εργασιών'),
        ),
    ]
