# Generated by Django 4.0.5 on 2022-07-07 12:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0014_rename_exit_account_credit_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Διαθέσιμο Υπόλοιπο (€)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, verbose_name='Περιγραφή'),
        ),
        migrations.AlterField(
            model_name='account',
            name='expenditure_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure_register.expenditureregister', verbose_name='Μητρώο Δεσμεύσεων'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό Πίστωσης'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='disposed_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ποσοστό Διάθεσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='computed_maturation_start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 8, 12, 1, 40, 409450, tzinfo=utc), verbose_name='Ημερομηνία έναρξης ωρίμανσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='computed_payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 8, 12, 1, 40, 409465, tzinfo=utc), verbose_name='Ημερομηνία δημιουργίας υποχρέωσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 6, 12, 1, 40, 409416, tzinfo=utc), verbose_name='Ημερομηνία παραλαβής αγαθών, υπηρεσιών ή εργασιών'),
        ),
    ]
