# Generated by Django 4.0.5 on 2022-07-12 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0017_remove_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Διαθέσιμο Υπόλοιπο (€)'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό Δέσμευσης'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='debit_protocol_number',
            field=models.CharField(max_length=10, verbose_name='Αριθμός πρωτ. απόφασης ανάληψης υποχρέωσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='computed_maturation_start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 13, 7, 39, 18, 921369, tzinfo=utc), verbose_name='Ημερομηνία έναρξης ωρίμανσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='computed_payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 13, 7, 39, 18, 921385, tzinfo=utc), verbose_name='Ημερομηνία δημιουργίας υποχρέωσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 7, 39, 18, 921336, tzinfo=utc), verbose_name='Ημερομηνία παραλαβής αγαθών, υπηρεσιών ή εργασιών'),
        ),
    ]
