# Generated by Django 4.0.5 on 2022-07-14 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0018_account_balance_alter_debit_debit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentDocument',
            new_name='Payment',
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='computed_maturation_start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 15, 10, 45, 52, 60932, tzinfo=utc), verbose_name='Ημερομηνία έναρξης ωρίμανσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='computed_payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 15, 10, 45, 52, 60948, tzinfo=utc), verbose_name='Ημερομηνία δημιουργίας υποχρέωσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='invoice_charge_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό τιμολογίου ή ισοδύναμου εγγράφου'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 13, 10, 45, 52, 60896, tzinfo=utc), verbose_name='Ημερομηνία λήξης προθεσμίας πληρωμής'),
        ),
    ]
