# Generated by Django 4.0.5 on 2022-09-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0024_alter_requestforpaymentorinvoice_computed_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='invoice_series',
            field=models.CharField(max_length=10, null=True, verbose_name='Σειρά τιμολογίου ή άλλου φορολογικού στοιχείου'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='service_acceptance_verification_date',
            field=models.DateField(null=True, verbose_name='Ημερομηνία έγκρισης παραλαβής αγαθών, υπηρεσιών ή εργασιών (Μόνο για εμπορικές συναλλαγές)'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='service_reception_date',
            field=models.DateField(null=True, verbose_name='Ημερομηνία παραλαβής αγαθών, υπηρεσιών ή εργασιών (Μόνο για εμπορικές συναλλαγές)'),
        ),
    ]
