# Generated by Django 4.0.5 on 2022-09-27 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0029_alter_requestforpaymentorinvoice_computed_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expenditure_register.requestforpaymentorinvoice', verbose_name='Τιμολόγιο'),
        ),
    ]
