# Generated by Django 4.0.5 on 2022-09-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0031_requestforpaymentorinvoice_invoice_reveral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestforpaymentorinvoice',
            name='invoice_reveral',
        ),
        migrations.RemoveField(
            model_name='requestforpaymentorinvoice',
            name='is_payment_reversal',
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='service_acceptance_verification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία έγκρισης παραλαβής αγαθών, υπηρεσιών ή εργασιών (Μόνο για εμπορικές συναλλαγές)'),
        ),
    ]
