# Generated by Django 4.0.5 on 2022-09-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0035_requestforpaymentorinvoice_owned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='credit_reform',
            field=models.CharField(choices=[('ΕΓΚΕΚΡΙΜΕΝΗ', 'ΕΓΚΕΚΡΙΜΕΝΗ'), ('ΑΝΑΜΟΡΦΩΣΗ', 'ΑΝΑΜΟΡΦΩΣΗ')], default='ΤΡΙΤΟΥΣ', max_length=100, verbose_name='Υποχρέωση προς'),
        ),
    ]
