# Generated by Django 4.0.5 on 2022-09-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0036_credit_credit_reform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='credit_reform',
            field=models.CharField(choices=[('ΕΓΚΕΚΡΙΜΕΝΗ', 'ΕΓΚΕΚΡΙΜΕΝΗ'), ('ΑΝΑΜΟΡΦΩΣΗ', 'ΑΝΑΜΟΡΦΩΣΗ')], default='ΕΓΚΕΚΡΙΜΕΝΗ', max_length=100, verbose_name='Τύπος Πίστωσης'),
        ),
    ]
