# Generated by Django 4.0.5 on 2022-10-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0037_alter_credit_credit_reform'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforpaymentorinvoice',
            name='invoice_created_by_us',
            field=models.BooleanField(default=False, verbose_name='Αυτόματη συμπλήρωση υπόλοιπων ημερομηνιών όταν η κατάσταση πληρωμής εκδόθηκε από την υπηρεσία μας.'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_reform',
            field=models.CharField(choices=[('ΕΓΚΕΚΡΙΜΕΝΗ', 'ΕΓΚΕΚΡΙΜΕΝΗ'), ('ΑΝΑΜΟΡΦΩΣΗ', 'ΑΝΑΜΟΡΦΩΣΗ')], default='ΑΝΑΜΟΡΦΩΣΗ', max_length=100, verbose_name='Τύπος Πίστωσης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='payment_in_advance',
            field=models.BooleanField(default=False, verbose_name='Πληρωμή μέσω Πάγιας Προκαταβολής ή Χρηματικού Εντάλματος Προπληρωμής'),
        ),
    ]
