# Generated by Django 4.0.5 on 2022-11-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0039_alter_expenditureregister_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='subcategory',
            field=models.CharField(choices=[('ΙΔΙΩΤΕΣ', 'ΙΔΙΩΤΕΣ'), ('ΥΠΕΡΩΡΙΕΣ ΔΙΟΙΚΗΤΙΚΩΝ', 'ΥΠΕΡΩΡΙΕΣ ΔΙΟΙΚΗΤΙΚΩΝ'), ('ΜΗ ΛΗΨΗ ΑΔΕΙΑΣ', 'ΜΗ ΛΗΨΗ ΑΔΕΙΑΣ'), ('ΑΠΟΖΗΜΙΩΣΗ ΣΑΒΒΑΤΑ-ΚΥΡΙΑΚΕΣ', 'ΑΠΟΖΗΜΙΩΣΗ ΣΑΒΒΑΤΑ-ΚΥΡΙΑΚΕΣ'), ('ΑΠΟΖΗΜΙΩΣΗ ΣΑΒΒΑΤΑ-ΚΥΡΙΑΚΕΣ (ΙΔΟΧ)', 'ΑΠΟΖΗΜΙΩΣΗ ΣΑΒΒΑΤΑ-ΚΥΡΙΑΚΕΣ (ΙΔΟΧ)'), ('ΥΠΕΡΩΡΙΕΣ', 'ΥΠΕΡΩΡΙΕΣ'), ('ΩΡΟΜΙΣΘΙΟΙ', 'ΩΡΟΜΙΣΘΙΟΙ'), ('ΥΠΕΡΩΡΙΕΣ ΣΕ ΒΟΥΛΕΥΤΙΚΑ, ΠΟΛΙΤΙΚΑ ΓΡΑΦΕΙΑ', 'ΥΠΕΡΩΡΙΕΣ ΣΕ ΒΟΥΛΕΥΤΙΚΑ, ΠΟΛΙΤΙΚΑ ΓΡΑΦΕΙΑ'), ('ΟΔΟΙΠΟΡΙΚΑ', 'ΟΔΟΙΠΟΡΙΚΑ'), ('ΕΞΟΔΑ ΜΕΤΑΚΙΝΗΣΗΣ ΜΑΘΗΤΩΝ', 'ΕΞΟΔΑ ΜΕΤΑΚΙΝΗΣΗΣ ΜΑΘΗΤΩΝ'), ('ΗΜΕΡΗΣΙΑ ΑΠΟΖΗΜΙΩΣΗ', 'ΗΜΕΡΗΣΙΑ ΑΠΟΖΗΜΙΩΣΗ'), ('ΕΠΙΤΡΟΠΕΣ ΙΔΟΧ', 'ΕΠΙΤΡΟΠΕΣ ΙΔΟΧ'), ('ΕΠΙΤΡΟΠΕΣ', 'ΕΠΙΤΡΟΠΕΣ'), ('ΤΟΚΟΙ ΑΠΌ ΕΚΤΕΛΕΣΗ ΔΙΚΑΣΤΙΚΩΝ ΑΠΟΦΆΣΕΩΝ', 'ΤΟΚΟΙ ΑΠΌ ΕΚΤΕΛΕΣΗ ΔΙΚΑΣΤΙΚΩΝ ΑΠΟΦΆΣΕΩΝ'), ('ΛΟΙΠΕΣ ΑΠΟΖΗΜΙΩΣΕΙΣ ΣΕ ΕΚΤΕΛΕΣΗ ΔΙΚΑΣΤΙΚΩΝ ΑΠΟΦΑΣΕΩΝ', 'ΛΟΙΠΕΣ ΑΠΟΖΗΜΙΩΣΕΙΣ ΣΕ ΕΚΤΕΛΕΣΗ ΔΙΚΑΣΤΙΚΩΝ ΑΠΟΦΑΣΕΩΝ'), ('ΔΙΚΑΣΤΙΚΑ', 'ΔΙΚΑΣΤΙΚΑ'), ('ΞΕΝΟΓΛΩΣΣΑ', 'ΞΕΝΟΓΛΩΣΣΑ'), ('ΕΞΟΔΑ ΔΙΑΝΥΚΤΕΡΕΥΣΗΣ', 'ΕΞΟΔΑ ΔΙΑΝΥΚΤΕΡΕΥΣΗΣ')], max_length=100, verbose_name='Υποκατηγορία'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ποσό Πίστωσης'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ποσό Δέσμευσης'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Συνολικό ποσό πληρωμής'),
        ),
        migrations.AlterField(
            model_name='recall',
            name='recall',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ποσό Ανάκλησης'),
        ),
        migrations.AlterField(
            model_name='requestforpaymentorinvoice',
            name='invoice_charge_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ποσό τιμολογίου ή ισοδύναμου εγγράφου'),
        ),
    ]
